// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/gogf/gf-demo-grpc/v2/internal/logic/user"
)
