// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gogf/gf-demo-grpc/internal/controller"
	"github.com/gogf/gf-demo-grpc/internal/logic"
	"github.com/gogf/gf-demo-grpc/internal/logic/user"
	"github.com/gogf/gf-demo-grpc/internal/server"
)

import (
	_ "github.com/gogf/gf-demo-grpc/internal/logic"
	_ "github.com/gogf/gf/contrib/drivers/mysql/v2"
)

// Injectors from wire.go:

// initApp di kratos application.
func initApp() *cmdApp {
	userUser := user.NewLogicUser()
	logicLogic := logic.NewLogic(userUser)
	controllerController := controller.NewController(logicLogic)
	grpcServer := server.NewGRPCServer(controllerController)
	ghttpServer := server.NewHTTPServer()
	mainCmdApp := newApp(grpcServer, ghttpServer)
	return mainCmdApp
}
